**Importing Libraries & Load Data**

In [1]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#display settings
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",100)

#plot setting
plt.style.use("ggplot")

In [2]:
#loading train dataset
with open("D:/Anaconda/archive/Data/trains.json","r") as file:
    train_data = json.load(file)

train_df = pd.json_normalize(train_data["features"])

In [3]:
# loading station data
with open("D:/Anaconda/archive/Data/schedules.json","r") as file:
    schedule_data = json.load(file)

schedule_df = pd.DataFrame(schedule_data)

In [4]:
#loading stations dataset
with open("D:/Anaconda/archive/Data/stations.json","r") as file:
    stations_data = json.load(file)

station_df = pd.json_normalize(stations_data["features"])

In [5]:
#checking data loaded successfully
print("Train Dataset Shape :", train_df.shape)
print("Station Dataset Shape :", station_df.shape)
print("Schedule Dataset Shape :", schedule_df.shape)

Train Dataset Shape : (5208, 24)
Station Dataset Shape : (8990, 9)
Schedule Dataset Shape : (417080, 8)

In [6]:
#Dataset Dimensions
print(f"Train Dataset Rows    : {train_df.shape[0]}")
print(f"Train Dataset Columns : {train_df.shape[1]}")

print(f"Stations Dataset Rows    : {station_df.shape[0]}")
print(f"Stations Dataset Columns : {station_df.shape[1]}")

print(f"Schedule Dataset Rows    : {schedule_df.shape[0]}")
print(f"Schedule Dataset Columns : {schedule_df.shape[1]}")

Train Dataset Rows    : 5208
Train Dataset Columns : 24
Stations Dataset Rows    : 8990
Stations Dataset Columns : 9
Schedule Dataset Rows    : 417080
Schedule Dataset Columns : 8

**Dataset Overview**

In [7]:
#Train Dataset Overview
print("="*70)
print("TRAIN DATASET OVERVIEW")
print("="*70)

print("Shape : ",train_df.shape)
print("\nColumns :")
print(train_df.columns.tolist())

print("\nData Types")
display(train_df.dtypes)

print("\nInformation")
train_df.info()

======================================================================
TRAIN DATASET OVERVIEW
======================================================================
Shape :  (5208, 24)

Columns :
['type', 'geometry.type', 'geometry.coordinates', 'properties.third_ac', 'properties.arrival', 'properties.from_station_code', 'properties.name', 'properties.zone', 'properties.chair_car', 'properties.first_class', 'properties.duration_m', 'properties.sleeper', 'properties.from_station_name', 'properties.number', 'properties.departure', 'properties.return_train', 'properties.to_station_code', 'properties.second_ac', 'properties.classes', 'properties.to_station_name', 'properties.duration_h', 'properties.type', 'properties.first_ac', 'properties.distance']

Data Types

type                             object
geometry.type                    object
geometry.coordinates             object
properties.third_ac               int64
properties.arrival               object
properties.from_station_code     object
properties.name                  object
properties.zone                  object
properties.chair_car              int64
properties.first_class            int64
properties.duration_m           float64
properties.sleeper                int64
properties.from_station_name     object
properties.number                object
properties.departure             object
properties.return_train          object
properties.to_station_code       object
properties.second_ac              int64
properties.classes               object
properties.to_station_name       object
properties.duration_h           float64
properties.type                  object
properties.first_ac               int64
properties.distance             float64
dtype: object

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5208 entries, 0 to 5207
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   type                          5208 non-null   object
 1   geometry.type                 5208 non-null   object
 2   geometry.coordinates          5208 non-null   object
 3   properties.third_ac           5208 non-null   int64
 4   properties.arrival            5208 non-null   object
 5   properties.from_station_code  5208 non-null   object
 6   properties.name               5208 non-null   object
 7   properties.zone               5208 non-null   object
 8   properties.chair_car          5208 non-null   int64
 9   properties.first_class        5208 non-null   int64
 10  properties.duration_m         5193 non-null   float64
 11  properties.sleeper            5208 non-null   int64
 12  properties.from_station_name  5208 non-null   object
 13  properties.number             5208 non-null   object
 14  properties.departure          5208 non-null   object
 15  properties.return_train       4609 non-null   object
 16  properties.to_station_code    5208 non-null   object
 17  properties.second_ac          5208 non-null   int64
 18  properties.classes            5193 non-null   object
 19  properties.to_station_name    5208 non-null   object
 20  properties.duration_h         5193 non-null   float64
 21  properties.type               5208 non-null   object
 22  properties.first_ac           5208 non-null   int64
 23  properties.distance           5193 non-null   float64
dtypes: float64(3), int64(6), object(15)
memory usage: 976.6+ KB

In [8]:
train_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
type,5208,1,Feature,5208,NaN,NaN,NaN,NaN,NaN,NaN,NaN
geometry.type,5208,1,LineString,5208,NaN,NaN,NaN,NaN,NaN,NaN,NaN
geometry.coordinates,5208,3919,"[[80.291601, 13.09034], [80.28293599999999, 13...",70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.third_ac,5208.0,NaN,NaN,NaN,0.31682,0.465281,0.0,0.0,0.0,1.0,1.0
properties.arrival,5208,370,09:30:00,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.from_station_code,5208,724,HWH,136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.name,5208,3948,Chennai Beach Velachery EMU,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.zone,5208,19,NR,628,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.chair_car,5208.0,NaN,NaN,NaN,0.077381,0.267221,0.0,0.0,0.0,0.0,1.0
properties.first_class,5208.0,NaN,NaN,NaN,0.032066,0.176192,0.0,0.0,0.0,0.0,1.0
properties.duration_m,5193.0,NaN,NaN,NaN,28.274408,17.294278,0.0,15.0,30.0,45.0,58.0
properties.sleeper,5208.0,NaN,NaN,NaN,0.33775,0.472988,0.0,0.0,0.0,1.0,1.0
properties.from_station_name,5208,720,HOWRAH JN,136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.number,5208,5208,84369,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.departure,5208,350,06:00:00,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.return_train,4609,4347,38442,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.to_station_code,5208,730,HWH,127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.second_ac,5208.0,NaN,NaN,NaN,0.272081,0.445074,0.0,0.0,0.0,1.0,1.0
properties.classes,5193,1,,5193,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.to_station_name,5208,727,HOWRAH JN,127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.duration_h,5193.0,NaN,NaN,NaN,10.766994,12.675426,0.0,2.0,6.0,15.0,85.0
properties.type,5208,17,Pass,2459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.first_ac,5208.0,NaN,NaN,NaN,0.084293,0.277854,0.0,0.0,0.0,0.0,1.0
properties.distance,5193.0,NaN,NaN,NaN,544.769305,696.791114,0.0,88.0,227.0,693.0,4279.0

In [9]:
#Station Dataset Overiew
print("="*70)
print("STATION DATASET OVERVIEW")
print("="*70)

print("Shape :", station_df.shape)

print("\nColumns :")
print(station_df.columns.tolist())

print("\nData Types")
display(station_df.dtypes)

print("\nInformation")
station_df.info()

======================================================================
STATION DATASET OVERVIEW
======================================================================
Shape : (8990, 9)

Columns :
['type', 'geometry.type', 'geometry.coordinates', 'properties.state', 'properties.code', 'properties.name', 'properties.zone', 'properties.address', 'geometry']

Data Types

type                     object
geometry.type            object
geometry.coordinates     object
properties.state         object
properties.code          object
properties.name          object
properties.zone          object
properties.address       object
geometry                float64
dtype: object

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8990 entries, 0 to 8989
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  8990 non-null   object
 1   geometry.type         8697 non-null   object
 2   geometry.coordinates  8697 non-null   object
 3   properties.state      4458 non-null   object
 4   properties.code       8990 non-null   object
 5   properties.name       8990 non-null   object
 6   properties.zone       4458 non-null   object
 7   properties.address    4458 non-null   object
 8   geometry              0 non-null      float64
dtypes: float64(1), object(8)
memory usage: 632.2+ KB

In [10]:
station_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
type,8990,1,Feature,8990,NaN,NaN,NaN,NaN,NaN,NaN,NaN
geometry.type,8697,1,Point,8697,NaN,NaN,NaN,NaN,NaN,NaN,NaN
geometry.coordinates,8697,8690,"[89.5868746, 26.0707762]",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.state,4458,30,Uttar Pradesh,529,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.code,8990,8990,MTDM,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.name,8990,8937,MAULA ALI,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.zone,4458,18,NR,590,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.address,4458,2724,,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN
geometry,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#schedule dataset overview
print("="*70)
print("SCHEDULE DATASET OVERVIEW")
print("="*70)

print("Shape :", schedule_df.shape)

print("\nColumns :")
print(schedule_df.columns.tolist())

print("\nData Types")
display(schedule_df.dtypes)

print("\nInformation")
schedule_df.info()

======================================================================
SCHEDULE DATASET OVERVIEW
======================================================================
Shape : (417080, 8)

Columns :
['arrival', 'day', 'train_name', 'station_name', 'station_code', 'id', 'train_number', 'departure']

Data Types

arrival          object
day             float64
train_name       object
station_name     object
station_code     object
id                int64
train_number     object
departure        object
dtype: object

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417080 entries, 0 to 417079
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   arrival       417080 non-null  object
 1   day           394519 non-null  float64
 2   train_name    417080 non-null  object
 3   station_name  417080 non-null  object
 4   station_code  417080 non-null  object
 5   id            417080 non-null  int64
 6   train_number  417080 non-null  object
 7   departure     417080 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 25.5+ MB

In [12]:
schedule_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
arrival,417080,1441,None,27835,NaN,NaN,NaN,NaN,NaN,NaN,NaN
day,394519.0,NaN,NaN,NaN,1.631901,0.670694,1.0,1.0,2.0,2.0,13.0
train_name,417080,3948,Garib Nawaz Express,1433,NaN,NaN,NaN,NaN,NaN,NaN,NaN
station_name,417080,8495,SABARMATI JN,342,NaN,NaN,NaN,NaN,NaN,NaN,NaN
station_code,417080,8539,CNB,312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id,417080.0,NaN,NaN,NaN,289502.693543,168749.701677,629.0,141134.75,289571.5,438992.25,560507.0
train_number,417080,5208,15905,698,NaN,NaN,NaN,NaN,NaN,NaN,NaN
departure,417080,1441,None,27827,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Data Cleaning &  Data Quality Check**

In [13]:
# Misiing Values 
print("Missing Values in Train Dataset")

train_missing = train_df.isnull().sum().sort_values(ascending = False)

tarin_missing = pd.DataFrame({
    "missing Values": train_missing,
    "Percenatge" : round(train_missing / len(train_df)*100,2)
})
train_missing

Missing Values in Train Dataset

properties.return_train         599
properties.classes               15
properties.duration_m            15
properties.duration_h            15
properties.distance              15
type                              0
geometry.coordinates              0
geometry.type                     0
properties.zone                   0
properties.name                   0
properties.from_station_code      0
properties.arrival                0
properties.third_ac               0
properties.sleeper                0
properties.first_class            0
properties.chair_car              0
properties.departure              0
properties.number                 0
properties.from_station_name      0
properties.to_station_code        0
properties.to_station_name        0
properties.second_ac              0
properties.type                   0
properties.first_ac               0
dtype: int64

In [14]:
#missing Values in Stations Dataset
print("Missing Values in Station Dataset")

station_missing = station_df.isnull().sum().sort_values(ascending=False)

station_missing = pd.DataFrame({
    "Missing Values": station_missing,
    "Percentage": round((station_missing / len(station_df)) * 100, 2)
})

station_missing

Missing Values in Station Dataset

                      Missing Values  Percentage
geometry                        8990      100.00
properties.zone                 4532       50.41
properties.state                4532       50.41
properties.address              4532       50.41
geometry.type                    293        3.26
geometry.coordinates             293        3.26
type                               0        0.00
properties.code                    0        0.00
properties.name                    0        0.00

In [15]:
#missing Values in Schedule Dataset
print("Missing Values in Schedule Dataset")

schedule_missing = schedule_df.isnull().sum().sort_values(ascending=False)

schedule_missing = pd.DataFrame({
    "Missing Values": schedule_missing,
    "Percentage": round((schedule_missing / len(schedule_df)) * 100, 2)
})

schedule_missing

Missing Values in Schedule Dataset

              Missing Values  Percentage
day                    22561        5.41
arrival                    0        0.00
train_name                 0        0.00
station_name               0        0.00
station_code               0        0.00
id                         0        0.00
train_number               0        0.00
departure                  0        0.00

In [24]:
print("Duplicate Records")
# In Station and train Dataset one column is list so duplicate function not work at list so we convert the list to tuple in both dataset
train_df["geometry.coordinates"] = train_df["geometry.coordinates"].apply(
    lambda x: tuple(map(tuple, x)) if isinstance(x, list) else x
)

station_df["geometry.coordinates"] = station_df["geometry.coordinates"].apply(
    lambda x: tuple(x) if isinstance(x, list) else x
)
print(f"Train Dataset    : {train_df.duplicated().sum()}")
print(f"Station Dataset  : {station_df.duplicated().sum()}")
print(f"Schedule Dataset : {schedule_df.duplicated().sum()}")

Duplicate Records
Train Dataset    : 0
Station Dataset  : 0
Schedule Dataset : 0

In [25]:
#Train Unique Value
print("Train Dataset")

for col in train_df.columns:
    print(f"{col:35} : {train_df[col].nunique()}")

Train Dataset
type                                : 1
geometry.type                       : 1
geometry.coordinates                : 3919
properties.third_ac                 : 2
properties.arrival                  : 370
properties.from_station_code        : 724
properties.name                     : 3948
properties.zone                     : 19
properties.chair_car                : 2
properties.first_class              : 2
properties.duration_m               : 54
properties.sleeper                  : 2
properties.from_station_name        : 720
properties.number                   : 5208
properties.departure                : 350
properties.return_train             : 4347
properties.to_station_code          : 730
properties.second_ac                : 2
properties.classes                  : 1
properties.to_station_name          : 727
properties.duration_h               : 73
properties.type                     : 17
properties.first_ac                 : 2
properties.distance                 : 1153

In [31]:
# unique values in Station Dataset
print("Sation Dataset")

for col in station_df.columns:
    print(f"{col:30} : {station_df[col].nunique()}")

Sation Dataset
type                           : 1
geometry.type                  : 1
geometry.coordinates           : 8690
properties.state               : 30
properties.code                : 8990
properties.name                : 8937
properties.zone                : 18
properties.address             : 2724
geometry                       : 0

In [32]:
#name column having missing values in train Dataset
print("Train Dataset")
train_df.columns[train_df.isnull().any()]

Train Dataset

Index(['properties.duration_m', 'properties.return_train',
       'properties.classes', 'properties.duration_h', 'properties.distance'],
      dtype='object')

In [33]:
#name of columns having missing values in train Dataset
print("Station Dataset")
station_df.columns[station_df.isnull().any()]

Station Dataset

Index(['geometry.type', 'geometry.coordinates', 'properties.state',
       'properties.zone', 'properties.address', 'geometry'],
      dtype='object')

In [35]:
#name of columns having missing values in schedule Dataset
print("Schedule Dataset")
schedule_df.columns[schedule_df.isnull().any()]

Schedule Dataset

Index(['day'], dtype='object')

In [46]:
# Percenatge of Missing Values
def missing_percentage(df):

    missing = pd.DataFrame({
        "Missing %": round(df.isnull().mean() * 100,2)
    })

    return missing[missing["Missing %"]>0].sort_values("Missing %",ascending=False)

train_missing_per=missing_percentage(train_df)
station_missing_per=missing_percentage(station_df)
schedule_missing_per=missing_percentage(schedule_df)
print("Train Dataset Missing Values % ")
print("-"*50)
print(train_missing_per)
print("-"*50)
print("Station Dataset Missing Values % ")
print("-"*50)
print(station_missing_per)
print("-"*50)
print("Schedule Dataset Missing Values %  ")
print("-"*50)
print(schedule_missing_per)

Train Dataset Missing Values %
--------------------------------------------------
                         Missing %
properties.return_train      11.50
properties.duration_m         0.29
properties.classes            0.29
properties.duration_h         0.29
properties.distance           0.29
--------------------------------------------------
Station Dataset Missing Values %
--------------------------------------------------
                      Missing %
geometry                 100.00
properties.state          50.41
properties.zone           50.41
properties.address        50.41
geometry.coordinates       3.26
geometry.type              3.26
--------------------------------------------------
Schedule Dataset Missing Values %
--------------------------------------------------
     Missing %
day       5.41